# Generated by Django 6.0.3 on 2026-04-13 18:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'JobTargets',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id_vacancy', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('company', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Vacancies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('preferred_region', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(help_text='The groups this user belongs to.', related_name='core_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GeneratedPaths',
            },
        ),
        migrations.CreateModel(
            name='PathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('generated_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.generatedpath')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
            options={
                'db_table': 'PathSteps',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='UserTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_target', to='core.jobtarget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserTargets',
                'unique_together': {('user', 'target_job')},
            },
        ),
        migrations.AddField(
            model_name='generatedpath',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_paths', to='core.usertarget'),
        ),
        migrations.CreateModel(
            name='SkillPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='core.skill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_set', to='core.skill')),
            ],
            options={
                'db_table': 'SkillPrerequisites',
                'constraints': [models.UniqueConstraint(fields=('skill', 'prerequisite_skill'), name='unique_skill')],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserSkills',
                'unique_together': {('user', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_skills', to='core.skill')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_skills', to='core.vacancy')),
            ],
            options={
                'db_table': 'VacancySkills',
                'constraints': [models.UniqueConstraint(fields=('vacancy', 'skill'), name='unique_vacancy_skill')],
            },
        ),
    ]
