# Generated by Django 6.0.3 on 2026-04-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vacancy_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('soft', 'Мягкий'), ('hard', 'Технический'), ('tool', 'Инструмент')], db_index=True, default='hard', max_length=10),
        ),
    ]
