# Generated by Django 6.0.3 on 2026-05-05 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skill_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='job_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobtarget'),
        ),
    ]
