# Generated by Django 6.0.3 on 2026-05-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vacancy_job_target'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usertarget',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='skillprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('skill', models.F('prerequisite_skill')), _negated=True), name='no_self_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='unique_user_skill'),
        ),
        migrations.AddConstraint(
            model_name='usertarget',
            constraint=models.UniqueConstraint(fields=('user', 'target_job'), name='unique_user_target'),
        ),
    ]
