# Generated by Django 6.0.3 on 2026-05-09 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userskill_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='fetched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='pathstep',
            constraint=models.UniqueConstraint(fields=('generated_path', 'step_order'), name='unique_step_order_per_path'),
        ),
    ]
