# Generated by Django 6.0.3 on 2026-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vacancy_fetched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtarget',
            name='search_terms',
            field=models.TextField(default=True),
        ),
    ]
