import logging
import pybreaker
from core.models import Skill

logger = logging.getLogger(__name__)
breaker = pybreaker.CircuitBreaker(fail_max=3, reset_timeout=60)

class SkillTypeClassifier:
    def __init__(self):
        # Словарь быстрых правил (можно вынести в БД или конфиг)
        self.rule_based_map = {
            'коммуникация': Skill.SkillType.SOFT,
            'терпение': Skill.SkillType.SOFT,
            'инициативность': Skill.SkillType.SOFT,
            'аналитическое мышление': Skill.SkillType.SOFT,
            'teamwork': Skill.SkillType.SOFT,
            'командная работа': Skill.SkillType.SOFT,
            'самостоятельная работа': Skill.SkillType.SOFT,
            'consistency': Skill.SkillType.SOFT,
            'research': Skill.SkillType.SOFT,
            'исследовательские навыки': Skill.SkillType.SOFT,
            'презентация': Skill.SkillType.SOFT,
            'внимательность к деталям': Skill.SkillType.SOFT,
            'грамотность': Skill.SkillType.SOFT,
            'документирование': Skill.SkillType.SOFT,
            'логическое мышление': Skill.SkillType.SOFT,
            'системное мышление': Skill.SkillType.SOFT,
            'структурирование информации': Skill.SkillType.SOFT,
            'гипотезирование': Skill.SkillType.SOFT,
            'самоорганизация': Skill.SkillType.SOFT,
            'управление временем': Skill.SkillType.SOFT,
            'критическое мышление': Skill.SkillType.SOFT,
            'стрессоустойчивость': Skill.SkillType.SOFT,
            'ответственность': Skill.SkillType.SOFT,
            'обучаемость': Skill.SkillType.SOFT,
            'работа в команде': Skill.SkillType.SOFT,
            'навыки презентации': Skill.SkillType.SOFT,
            'деловая коммуникация': Skill.SkillType.SOFT,
            'ведение переговоров': Skill.SkillType.SOFT,
            'клиентоориентированность': Skill.SkillType.SOFT,
            'лидерство': Skill.SkillType.SOFT,
            'менторство': Skill.SkillType.SOFT,
            'адаптивность': Skill.SkillType.SOFT,
            'multitasking': Skill.SkillType.SOFT,
            'организованность': Skill.SkillType.SOFT,
            'целеустремленность': Skill.SkillType.SOFT,
            # ... все soft и tool
            'docker': Skill.SkillType.TOOL,
            'pytest': Skill.SkillType.TOOL,
            'git': Skill.SkillType.TOOL,
            'grafana': Skill.SkillType.TOOL,
            'kubernetes': Skill.SkillType.TOOL,
            'apache airflow': Skill.SkillType.TOOL,
            'airflow': Skill.SkillType.TOOL,
            'apache kafka': Skill.SkillType.TOOL,
            'kafka': Skill.SkillType.TOOL,
            'clickhouse': Skill.SkillType.TOOL,
            'postgresql': Skill.SkillType.TOOL,
            'mysql': Skill.SkillType.TOOL,
            'microsoft sql server': Skill.SkillType.TOOL,
            'sql server': Skill.SkillType.TOOL,
            'redis': Skill.SkillType.TOOL,
            'celery': Skill.SkillType.TOOL,
            'rabbitmq': Skill.SkillType.TOOL,
            'apache spark': Skill.SkillType.TOOL,
            'spark': Skill.SkillType.TOOL,
            'hadoop': Skill.SkillType.TOOL,
            'greenplum': Skill.SkillType.TOOL,
            'vertica': Skill.SkillType.TOOL,
            'tableau': Skill.SkillType.TOOL,
            'power bi': Skill.SkillType.TOOL,
            'powerbi': Skill.SkillType.TOOL,
            'apache superset': Skill.SkillType.TOOL,
            'superset': Skill.SkillType.TOOL,
            'qlik': Skill.SkillType.TOOL,
            'finebi': Skill.SkillType.TOOL,
            'excel': Skill.SkillType.TOOL,
            'microsoft excel': Skill.SkillType.TOOL,
            'google sheets': Skill.SkillType.TOOL,
            'powerpoint': Skill.SkillType.TOOL,
            'microsoft powerpoint': Skill.SkillType.TOOL,
            'python': Skill.SkillType.TOOL,          # язык программирования → инструмент
            'pandas': Skill.SkillType.TOOL,
            'numpy': Skill.SkillType.TOOL,
            'scipy': Skill.SkillType.TOOL,
            'statsmodels': Skill.SkillType.TOOL,
            'scikit-learn': Skill.SkillType.TOOL,
            'tensorflow': Skill.SkillType.TOOL,
            'pytorch': Skill.SkillType.TOOL,
            'keras': Skill.SkillType.TOOL,
            'sqlalchemy': Skill.SkillType.TOOL,
            'django': Skill.SkillType.TOOL,
            'fastapi': Skill.SkillType.TOOL,
            'flask': Skill.SkillType.TOOL,
            'asyncio': Skill.SkillType.TOOL,
            'aiohttp': Skill.SkillType.TOOL,
            'celery': Skill.SkillType.TOOL,
            'bash': Skill.SkillType.TOOL,
            'linux': Skill.SkillType.TOOL,
            'gitlab': Skill.SkillType.TOOL,
            'github actions': Skill.SkillType.TOOL,
            'ci/cd': Skill.SkillType.TOOL,
            'jenkins': Skill.SkillType.TOOL,
            'teamcity': Skill.SkillType.TOOL,
            'jira': Skill.SkillType.TOOL,
            'confluence': Skill.SkillType.TOOL,
            'slack': Skill.SkillType.TOOL,
            'trello': Skill.SkillType.TOOL,
            'notion': Skill.SkillType.TOOL,
            'openwebui': Skill.SkillType.TOOL,
            'crewai': Skill.SkillType.TOOL,
            'langchain': Skill.SkillType.TOOL,
            'llama index': Skill.SkillType.TOOL,
            'openai api': Skill.SkillType.TOOL,
            'gigachat': Skill.SkillType.TOOL,
            'deepseek': Skill.SkillType.TOOL,
            'cursor': Skill.SkillType.TOOL,
            'n8n': Skill.SkillType.TOOL,
            'sparql': Skill.SkillType.TOOL,
            'dbt': Skill.SkillType.TOOL,
            'dbt core': Skill.SkillType.TOOL,
            'looker': Skill.SkillType.TOOL,
            'metabase': Skill.SkillType.TOOL,
            'redash': Skill.SkillType.TOOL,
            'mode analytics': Skill.SkillType.TOOL,
            'thoughtspot': Skill.SkillType.TOOL,
            'sas': Skill.SkillType.TOOL,
            'spss': Skill.SkillType.TOOL,
            'stata': Skill.SkillType.TOOL,
            'matlab': Skill.SkillType.TOOL,
            'r (programming language)': Skill.SkillType.TOOL,
            'r': Skill.SkillType.TOOL,
            'vba': Skill.SkillType.TOOL,
            'power query': Skill.SkillType.TOOL,
            'dax': Skill.SkillType.TOOL,
            'mdx': Skill.SkillType.TOOL,
            'google analytics': Skill.SkillType.TOOL,
            'yt (яндекс.метрика)': Skill.SkillType.TOOL,
            'appmetrica': Skill.SkillType.TOOL,
            'mixpanel': Skill.SkillType.TOOL,
            'amplitude': Skill.SkillType.TOOL,
            'segment': Skill.SkillType.TOOL,
            'gtm': Skill.SkillType.TOOL,
            'hotjar': Skill.SkillType.TOOL,
            'crazyegg': Skill.SkillType.TOOL,
            'optimizely': Skill.SkillType.TOOL,
        }

    def classify(self, skill_name: str) -> str:
        if not skill_name:
            return Skill.SkillType.HARD

        lower_name = skill_name.lower()
        if lower_name in self.rule_based_map:
            return self.rule_based_map[lower_name]
