from .GeneratePathView import GeneratePathView
from .PathHistoryView import PathHistoryView
from .ProfileView import ProfileView
from .RegisterView import RegisterView
from .JobTargetViewSet import JobTargetViewSet
from .UserSkillViewSet import UserSkillViewSet
from .UserTargetViewSet import UserTargetViewSet
from .SkillViewSet import SkillViewSet
from .AdminViewSet import AdminJobTargetViewSet
from .AdminViewSet import FetchVacanciesAdminView